name: Next.js Build & Static Export

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch: # Added for manual testing

concurrency:
  # Prevent overlapping runs on the same branch.
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    name: Build, Lint, and Export Static Site
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      # Step 1: Set up Node.js Environment with Built-in Caching
      # This step replaces your old Step 2 and Step 3 (npm global cache).
      - name: Use Node.js 18.x and Cache npm modules
        uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: 'npm' # Use built-in caching for global npm dependencies

      # Step 2: Cache Next.js build cache (Still necessary for speed)
      - name: Cache Next.js build cache
        uses: actions/cache@v4
        with:
          # Note: The 'out' folder is the static export, .next/cache is the build speedup cache.
          path: |
            .next/cache
            node_modules # Add node_modules here for dependency reuse
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      # Step 3: Install dependencies
      # Simplified to npm ci, as this is best practice and ensures a clean build.
      - name: Install dependencies
        run: npm ci

      # Step 4: Run lint check
      - name: Lint
        run: npm run lint

      # Step 5: Build Next.js project (generates optimized `.next` folder)
      - name: Build Next.js project
        run: npm run build
        
      # Step 6: Package the full build output (optional but simplifies artifact handling)
      - name: Package full build output
        run: zip -r project-harmony-frontend-build.zip .next public package.json
        # Includes .next (compiled output), public (assets), and package.json (context)

      # Step 7: Upload the packaged artifact (renamed for clarity)
      - name: Upload full build artifact
        uses: actions/upload-artifact@v4
        with:
          name: project-harmony-frontend-build
          path: project-harmony-frontend-build.zip
          # Path points to the single zip file